### ISSUE TITLE
Make metric.Gauge a float64

### ISSUE THREAD

**Issue by nightlyone** [peterbourgon/gokit#11]
Rationale: Gauges are measured in various accuracies and are difficult to rescale later once you already have collected data. The performance impact seems negligible, since we only Set and Add Gauges. Doubling the memory consumption per Gauge seems worth the result.

**Comment by peterbourgon** [comment]
Originally Gauge _was_ float64, but I changed to int64 after reviewing [codahale/metrics](https://github.com/codahale/metrics/blob/518ef000ddd9a697502315949ee08a155693c9b2/metrics.go#L100). I like the integer consistency of the metrics interfaces, especially as [e.g. Histograms are implemented in terms of Gauges in some places](https://github.com/peterbourgon/gokit/blob/70038db395332ed4fad6b5a341d8a6aef77b453b/metrics/expvar/expvar.go#L65). And I can't think of many (any?) things that are Gauge-able that can't be reduced to integers. Can you link me to some code in the wild that requires Gauges-as-floats?

**Comment by peterbourgon** [comment]
Closed pending further comments...
