### ISSUE TITLE
Debug HTTP server

### ISSUE THREAD

**Issue by jtolds** [peterbourgon/gokit#2]
There are a lot of useful debug HTTP handlers to add for processes. Stuff like pprof, job management endpoints (quitquitquit, abortabortabort, health are common), process-level metrics, etc. 

It would be nice to have gokit automatically spin up a debug port for listening with a bunch of defined (and possibly extendable) debug HTTP handlers.

This issue would benefit from #1, since by default we could have it listen on 127.0.0.1:0, but be configurable to be something else.

**Comment by jtolds** [comment]
the spacemonkeygo/monitor project has an HTTP handler that returns a list of running process tasks, in addition to a handler that returns a list of key/value stats about the process (environment information, any programmer-added metrics, etc)

**Comment by peterbourgon** [comment]
Common read-only stdlib debug information like pprof, expvar, and simple health checking should indeed be made accessible, probably by default. I think it's up for debate whether they should be bound to a specific debug port and therefore exist in isolation, or multiplexed onto the HTTP port used in an HTTP transport. Probably that should be user-definable.

We may also define a set of utility endpoints like quitquitquit, though I'd prefer to give that opt-in semantics.

It all feels like it's properly in the domain of package server.

**Comment by adg** [comment]
On 13 February 2015 at 05:57, Peter Bourgon <notifications@github.com>
wrote:

> It all feels like it's properly in the domain of package server.


Agree
