### ISSUE TITLE
Contexts

### ISSUE THREAD

**Issue by jtolds** [peterbourgon/gokit#3]
The server package should probably have a convention for threading contexts (blog.golang.org/context) through from service handlers all the way down to client requests. In the absence of thread-local-storage (which I believe many Zipkin clients end up using), we need a way to pass through request context from service to service.

(I feel compelled to point out that https://github.com/jtolds/gls is technically a possibility, but it's horrible and I would vote against it)

**Comment by jtolds** [comment]
http://godoc.org/github.com/spacemonkeygo/monitor/trace is one possible example of the way this benefits things. 

Internally at Space Monkey we also have a disk operation library that distinguishes disk operations as being background (cron-type jobs or something) or foreground operations (user-requested) using the existing context, to determine what priority in our application-level disk queue the operation should go (in an attempt to keep low-level queues shallow)

**Comment by peterbourgon** [comment]
Yes, package server will need to make sure contextual information isn't lost in translation between services, and I definitely intend to leverage package context for that. Hopefully it's possible to implement without modifying server interface definitions, i.e. by mandatory chaining of a Contextual (or similar) handler. All to be determined. 

If you're interested in package server, maybe you'd like to join Freenode #gokit and find some other interested parties to take ownership of [the initial package server RFC](https://github.com/peterbourgon/gokit/tree/master/rfc/rfc000-package-server.md)?

**Comment by tsenart** [comment]
@peterbourgon: Would it make sense to create Github issues for each of the RFCs, where structured, scoped pre-proposal discussion can take place? I think focus is paramount given the spectrum of problems to be solved here.

**Comment by peterbourgon** [comment]
@tsenart yes, I think that's a logical next step.

**Comment by bg451** [comment]
@tsenaet +1 to that idea.

**Comment by peterbourgon** [comment]
This will be addressed in the first-draft implementation.
