### ISSUE TITLE
Worth taking a look at Thrift and gRPC (both have Go support)? EOM

### ISSUE THREAD

**Issue by oleksandr** [peterbourgon/gokit#30]

**Comment by peterbourgon** [comment]
Both are target transports. Check out [the package-server branch](https://github.com/peterbourgon/gokit/tree/package-server), specifically [here](https://github.com/peterbourgon/gokit/blob/package-server/addsvc/main.go#L75) and [here](https://github.com/peterbourgon/gokit/blob/package-server/addsvc/main.go#L115).
