### ISSUE TITLE
package log needs a Logf or Printf method

### ISSUE THREAD

**Issue by peterbourgon** [peterbourgon/gokit#35]
There should be an easy way to do e.g.

```go
logger.Logf("server started on %s", listenAddress) // default/predefined key
logger.Printf("msgkey", "%d queued, %d finished", queued, finished) // explicit key
```

**Comment by ChrisHines** [comment]
-1

I disagree. That will muddle the API and it will also confuse the opinion that structured logging is preferred. Finally there is always fmt.Sprintf for those that insist on throwing away structure and type information.

**Comment by peterbourgon** [comment]
This use case emerged as I was migrating the demo addsvc over to universal gokit/log, and found several cases where I needed the functionality. As I reflected on those cases, I realize there's lots of classes of information that I want to end up in logs which is properly generated with Printf-style constructions. I'm happy to solve it with a wrapper type or function, but I'm not happy to require users to `fmt.Sprintf` their values.

```go
log.Printf(logger, "msg", "listener started on %s", *listenAddr) // 1
logger.Logf("msg", "listener started on %s", *listenAddr) // 2

loggerf := log.Loggerf(logger)
loggerf.Log("msg", "listener started on %s", *listenAddr) // 3
```

I think I prefer option 1. We have some precedent for the pattern with `log.With`; unlike option 2, it doesn't require extending the nice & minimal `type Logger interface` with another method; unlike option 3, it doesn't require the ceremony of an additional type or type-instance.

Am I missing anything? Votes or opinions? @tsenart?

**Comment by ChrisHines** [comment]
Why not this?
```go
logger.Log("msg", "listener started", "addr", *listenAddr)
```
That's how I do it in my apps today, although since those apps use log15.v2 presently, the "msg" key is implied, so the log15 version looks like this.
```go
log15.Info("listener started", "addr", *listenAddr)
```
Are you sure you want fmt.Sprintf style for this? It seems that maybe it's the explanatory "listener started" piece that gives that illusion.

**Comment by peterbourgon** [comment]
That's very interesting. Let me think on that for awhile. Maybe it's sufficient.

**Comment by ChrisHines** [comment]
For additional commentary, see https://github.com/inconshreveable/log15/issues/14 in which the same request was rejected.

**Comment by peterbourgon** [comment]
Wow, everything old is new again :) (This sort of thing is exactly why I raised #36, for the record.)

**Comment by peterbourgon** [comment]
I'm satisfied to use [a more structured style of logging](https://github.com/peterbourgon/gokit/blob/3ac6ef0d5d31a51ad4f8cc4ec4c0f03c4b5eb48c/addsvc/main.go#L103) for my original use case. We'll see how long that lasts :)
