### ISSUE TITLE
Can we just adapt e.g. log15 or logrus instead of building and maintaining our own package log?

### ISSUE THREAD

**Issue by peterbourgon** [peterbourgon/gokit#36]
- https://github.com/inconshreveable/log15
- https://github.com/Sirupsen/logrus

@ChrisHines @tsenart

**Comment by ChrisHines** [comment]
That doesn't change much for me. I'm already one of the two maintainers for log15. I see the gokit/log package as an opportunity to address some issues with the current log15 API that we have discussed, but require breaking changes and thus bumping the API version from 2 to 3, which make it difficult to justify doing in an established project. In my mind gokit/log is basically log15.v3.

**Comment by peterbourgon** [comment]
Thanks for your clarification. I don't have super strong opinions on the change, I'm just noticing that we're spending some nontrivial effort, and wondering if it's justified. But I defer to your domain expertise. I'm also happy to encode the strong opinions I _do_ have about structured logging :)

Thanks for the response!
