### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by aybabtme** [peterbourgon/gokit#9]
oh hey, would be nice to have Sourcegraph enabled on this repo, would help with code reviews. For instance I was reading #6 and the large diff would be easier to read with type annotation =P

## this is a canned message they provide:

I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with gokit. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable gokit on @Sourcegraph by going to https://sourcegraph.com/github.com/peterbourgon/gokit and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by peterbourgon** [comment]
I did it I think!

**Comment by sqs** [comment]
Cool!

I noticed a couple of issues that we'll fix on our end (Godeps support, etc.) But it's working...try hovering your mouse over some of the idents at https://sourcegraph.com/github.com/peterbourgon/gokit/.pulls/6/files?Filter=metrics%2Fprometheus.go.

**Comment by aybabtme** [comment]
:+1:
